AllCops:
  Exclude:
    - "vendor/**/*"
  DisplayCopNames: true

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/CollectionMethods:
  Description: Preferred collection methods.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#map-find-select-reduce-size
  Enabled: true
  PreferredMethods:
    collect: map
    collect!: map!
    find: detect
    find_all: select
    reduce: reduce

Style/Documentation:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 5

Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

Style/ModuleFunction:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/SignalException:
  EnforcedStyle: only_raise

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  Exclude:
    - "**/*.rake"
    - "Rakefile"

Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

Lint/AssignmentInCondition:
  Enabled: false

Lint/BlockAlignment:
  Enabled: false

Metrics/MethodLength:
  Max: 12

FileName:
  Exclude:
    - 'lib/activerecord-sharding.rb'
    - 'spec/tasks/activerecord-sharding_spec.rb'
